version: "3"
services:

  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    restart: always
    volumes:
      - .:/app/
      - /app/user/node_modules

  game:
    build:
      dockerfile: Dockerfile
      context: ./game
    restart: always
    volumes:
      - .:/app
      - /app/game/node_modules

  campaign:
    build:
      dockerfile: Dockerfile
      context: ./campaign
    restart: always
    volumes:
      - .:/app
      - /app/campaign/node_modules

  gateway_proxy:
    image: nginx:latest
    ports:
      - 8080:8080
    depends_on:
      - user_proxy
      - game_proxy
      - campaign_proxy
    volumes:
      - .:/app/
      - ./nginx.conf:/etc/nginx/nginx.conf

  user_proxy:
    image: nginx:latest
    ports:
      - 8081:8081
    depends_on:
      - user
    volumes:
      - .:/app/
      - ./user/nginx.conf:/etc/nginx/nginx.conf

  game_proxy:
    image: nginx:latest
    ports:
      - 8082:8082
    depends_on:
      - game
    volumes:
      - .:/app/
      - ./game/nginx.conf:/etc/nginx/nginx.conf

  campaign_proxy:
    image: nginx:latest
    ports:
      - 8083:8083
    depends_on:
      - campaign
    volumes:
      - .:/app/
      - ./campaign/nginx.conf:/etc/nginx/nginx.conf