version: "3"
services:

  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    restart: always
    volumes:
      - .:/app/
      - /app/user/node_modules

  game:
    build:
      dockerfile: Dockerfile
      context: ./game
    restart: always
    volumes:
      - .:/app
      - /app/game/node_modules

  campaign:
    build:
      dockerfile: Dockerfile
      context: ./campaign
    restart: always
    volumes:
      - .:/app
      - /app/campaign/node_modules

  # notification:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./notification
  #   restart: always
  #   volumes:
  #     - .:/app
  #     - /app/notification/node_modules

  gateway_proxy:
    image: nginx:latest
    ports:
      - 8000:8000
    depends_on:
      - user
      - game
      - campaign
      # - notification
    volumes:
      - .:/app/
      - ./nginx.conf:/etc/nginx/nginx.conf